"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase-browser";
type Req={id:string;email:string;name:string|null;phone:string|null;company_id:string|null;status:string;created_at:string};
type Company={id:string;name:string;slug:string};
export default function Admin(){
 const s=createClient();const [requests,setRequests]=useState<Req[]>([]);const [companies,setCompanies]=useState<Company[]>([]);const [name,setName]=useState("");const [slug,setSlug]=useState("");const [msg,setMsg]=useState("");
 async function load(){const [{data:r},{data:c}]=await Promise.all([s.from("access_requests").select("*").order("created_at",{ascending:false}),s.from("companies").select("id,name,slug").order("name")]);setRequests(r||[]);setCompanies(c||[])}
 useEffect(()=>{load()},[]);
 async function createCompany(e:React.FormEvent){e.preventDefault();const clean=slug.trim().toLowerCase().replace(/[^a-z0-9-]+/g,"-").replace(/^-|-$/g,"");const {data,error}=await s.from("companies").insert({name:name.trim(),slug:clean}).select().single();if(error){setMsg(error.message);return}await s.from("subscriptions").insert({company_id:data.id,plan:"annual",status:"active",started_at:new Date().toISOString(),expires_at:new Date(Date.now()+365*24*60*60*1000).toISOString()});setName("");setSlug("");setMsg("Empresa criada e plano anual iniciado.");load()}
 async function approve(r:Req,id:string){if(!id){setMsg("Escolha a empresa.");return}const {error}=await s.from("access_requests").update({status:"approved",company_id:id,reviewed_at:new Date().toISOString()}).eq("id",r.id);setMsg(error?"Erro: "+error.message:"Cliente autorizado ✓");load()}
 async function reject(r:Req){const {error}=await s.from("access_requests").update({status:"rejected",reviewed_at:new Date().toISOString()}).eq("id",r.id);setMsg(error?"Erro: "+error.message:"Pedido recusado.");load()}
 return <main className="app"><div className="topbar"><div><b>NFC Smart</b><span>Admin Master • controle total</span></div><div className="toplinks"><Link href="/dashboard">Dashboard</Link><Link href="/">Página inicial</Link></div></div><div className="admin-wrap"><h1>Painel do dono</h1><p className="muted">Crie empresas, vincule clientes e autorize o acesso ao sistema.</p>{msg&&<div className="notice">{msg}</div>}
 <section className="panel admin-section"><h2>Nova empresa</h2><form className="admin-form" onSubmit={createCompany}><input placeholder="Nome da empresa" value={name} onChange={e=>setName(e.target.value)} required/><input placeholder="slug-da-empresa" value={slug} onChange={e=>setSlug(e.target.value)} required/><button className="btn">Criar empresa</button></form></section>
 <section className="panel admin-section"><div className="row-between"><h2>Solicitações de acesso</h2><span className="muted">{requests.filter(x=>x.status==="pending").length} pendente(s)</span></div><div className="request-list">{requests.map(r=><Request key={r.id} r={r} companies={companies} approve={approve} reject={reject}/>)}</div></section>
 <section className="panel admin-section"><h2>Empresas</h2>{companies.length===0?<p className="muted">Nenhuma empresa criada.</p>:companies.map(c=><div className="company-row" key={c.id}><b>{c.name}</b><span>/{c.slug}</span><Link href="/dashboard/editor">Editar página →</Link></div>)}</section>
 </div></main>
}
function Request({r,companies,approve,reject}:{r:Req;companies:Company[];approve:(r:Req,id:string)=>void;reject:(r:Req)=>void}){const [id,setId]=useState(r.company_id||"");return <div className="request"><div><b>{r.name||"Cliente"}</b><div>{r.email}</div>{r.phone&&<small>{r.phone}</small>}<small className="status">{r.status}</small></div>{r.status==="pending"&&<div className="request-actions"><select value={id} onChange={e=>setId(e.target.value)}><option value="">Escolher empresa</option>{companies.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><button className="btn" onClick={()=>approve(r,id)}>Autorizar</button><button className="icon-btn" onClick={()=>reject(r)}>Recusar</button></div>}</div>}
