"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase-browser";
export default function Editor(){
 const sb=createClient(),router=useRouter();
 const [id,setId]=useState(""),[f,setF]=useState({name:"",description:"",bg:"#f6f6f3",primary:"#111111",text:"#111111",secondary:"#777777",buttonText:"#ffffff",logo:"",cover:"",phone:"",whatsapp:"",phoneEnabled:true,whatsappEnabled:true}),[msg,setMsg]=useState("");
 useEffect(()=>{(async()=>{const {data:{user}}=await sb.auth.getUser();if(!user)return router.push("/login");const {data:m}=await sb.from("company_members").select("company_id").eq("user_id",user.id).maybeSingle();if(!m)return router.push("/acesso-pendente");setId(m.company_id);const {data:c}=await sb.from("companies").select("*").eq("id",m.company_id).single();if(!c)return;setF({name:c.name,description:c.description||"",bg:c.background_color||"#f6f6f3",primary:c.primary_color||"#111111",text:c.text_color||"#111111",secondary:c.secondary_text_color||"#777777",buttonText:c.button_text_color||"#ffffff",logo:c.logo_url||"",cover:c.cover_url||"",phone:c.phone||"",whatsapp:c.whatsapp||"",phoneEnabled:c.phone_enabled!==false,whatsappEnabled:c.whatsapp_enabled!==false})})()},[]);
 async function upload(file:File,key:"logo"|"cover"){const path=id+"/"+key+"-"+crypto.randomUUID()+"-"+file.name.replace(/[^a-zA-Z0-9.]/g,"");const up=await sb.storage.from("company-assets").upload(path,file,{upsert:true});if(up.error)return setMsg(up.error.message);const u=sb.storage.from("company-assets").getPublicUrl(path).data.publicUrl;setF(v=>({...v,[key]:u}))}
 async function save(){setMsg("Salvando…");const a=await sb.from("companies").update({name:f.name,description:f.description,background_color:f.bg,primary_color:f.primary,text_color:f.text,secondary_text_color:f.secondary,button_text_color:f.buttonText,logo_url:f.logo,cover_url:f.cover,phone:f.phone,whatsapp:f.whatsapp,phone_enabled:f.phoneEnabled,whatsapp_enabled:f.whatsappEnabled,updated_at:new Date().toISOString()}).eq("id",id);const p=await sb.from("profiles").upsert({company_id:id,display_name:f.name,avatar_url:f.logo,secondary_image_url:f.cover,updated_at:new Date().toISOString()},{onConflict:"company_id"});setMsg(a.error?a.error.message:p.error?p.error.message:"Alterações salvas.")}
 return <main className="editor"><header><button onClick={()=>router.back()}>← Voltar</button><b className="logo">NFC<span>SMART</span></b><button className="btn dark" onClick={save}>Salvar</button></header><section className="editor-layout"><div className="editor-card"><p className="eyebrow">IDENTIDADE E ESTILO</p><h1>Monte sua página.</h1>
 <label>Nome<input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label>Descrição<textarea value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></label>
 <div className="uploadrow"><label>Foto de perfil<input type="file" accept="image/*" onChange={e=>e.target.files&&upload(e.target.files[0],"logo")}/>{f.logo&&<img className="thumb round" src={f.logo}/>}</label><label>Foto secundária<input type="file" accept="image/*" onChange={e=>e.target.files&&upload(e.target.files[0],"cover")}/>{f.cover&&<img className="thumb" src={f.cover}/>}</label></div>
 <h3>Cores da página</h3><div className="colors color-grid"><label>Fundo<input type="color" value={f.bg} onChange={e=>setF({...f,bg:e.target.value})}/></label><label>Texto principal<input type="color" value={f.text} onChange={e=>setF({...f,text:e.target.value})}/></label><label>Texto secundário<input type="color" value={f.secondary} onChange={e=>setF({...f,secondary:e.target.value})}/></label><label>Fundo dos botões<input type="color" value={f.primary} onChange={e=>setF({...f,primary:e.target.value})}/></label><label>Texto dos botões<input type="color" value={f.buttonText} onChange={e=>setF({...f,buttonText:e.target.value})}/></label></div>
 <h3>Contato</h3><label>Telefone<input value={f.phone} placeholder="(61) 99999-9999" onChange={e=>setF({...f,phone:e.target.value})}/></label><label className="checkline"><input type="checkbox" checked={f.phoneEnabled} onChange={e=>setF({...f,phoneEnabled:e.target.checked})}/> Mostrar telefone</label><label>WhatsApp<input value={f.whatsapp} placeholder="(61) 99999-9999" onChange={e=>setF({...f,whatsapp:e.target.value})}/></label><label className="checkline"><input type="checkbox" checked={f.whatsappEnabled} onChange={e=>setF({...f,whatsappEnabled:e.target.checked})}/> Este número possui WhatsApp / Mostrar botão</label><p className="muted contact-help">Se não houver WhatsApp, o cliente continua podendo ligar ou copiar o número.</p>
 {msg&&<div className="notice">{msg}</div>}</div>
 <div className="phone" style={{background:f.bg,color:f.text}}><div className="phone-cover" style={{backgroundImage:f.cover?"url("+f.cover+")":undefined}}/><div className="phone-avatar" style={{borderColor:f.bg}}>{f.logo?<img src={f.logo}/>:f.name[0]}</div><h3>{f.name}</h3><p style={{color:f.secondary}}>{f.description}</p><div className="phone-grid"><span style={{background:f.primary,color:f.buttonText}}>WhatsApp</span><span style={{background:f.primary,color:f.buttonText}}>Instagram</span><span style={{background:f.primary,color:f.buttonText}}>PIX</span><span style={{background:f.primary,color:f.buttonText}}>Google</span></div></div>
 </section></main>
}